%YAML:1.0

# Path settings
IMACQ_VIDEO_PATH:"D:/Data/Endo-trainer/DrAndre_1_0_Deg_ST_Aux.avi"

LOAD_MODEL: 0
MODEL_PATH:"D:/Official/Programs/endo_tracking/opentld/OpenTLD/Result/model_DrAndre_2_0_Deg_ST_Aux"

PRINT_RESULT_FILE:"D:/Data/Endo-trainer/Result/DrAndre_1_0_Deg_ST_Aux.txt"

SAVE_OUTPUT:1
SAVE_DIRECTORY:""

EXPORT_MODEL_AFTER_RUN:0
MODEL_EXPORT_FILE:"D:/Official/Programs/endo_tracking/opentld/OpenTLD/Result/test"

# defaults used in the program;
PEGBOUNDINGBOX_X:160
PEGBOUNDINGBOX_Y: 240
PEGBOUNDINGBOX_WIDTH: 830
PEGBOUNDINGBOX_HEIGHT:550
PEGSATURATION_MINVALUE:120
MIN_PEG_SIZE:  25
HUE_THRESHVAL_RING: 20.0
STATIONARY:"stationary"
STABLE_COUNT: 5
IMACQ_IMGS: 0 
IMACQ_CAM: 1 
IMACQ_VID: 2 
IMACQ_LIVESIM: 3
IMACQ_STREAM: 4
THRESHOLD: 0.6
LEARNING_ENABLED: 1
SHOW_OUTPUT: 1
SHOW_NOT_CONFIDENT: 1
SHOW_COLOR_IMAGE: 0
SHOW_FOREGROUND: 0
TLD_WITH_TRACKER_ONLY: 0
STATIONARY_FRAME_COUNT: 20
CONSECUTIVE_FRAME_COUNT: 10
NO_OF_IMAGES_HITTING_DETECTION: 10
HITTING_THRESHOLD: 30
SEED: 0
